import type { Product, Category, SiteSettings, Coupon } from './types'

export const categories: Category[] = [
  { id: '1', name: 'اكسسوارات', nameEn: 'Accessories', slug: 'accessories', image: '/image/categories/acc.jpg', productCount: 12 },
  { id: '2', name: 'عطورات', nameEn: 'Perfumes', slug: 'perfumes', image: '/image/products/etr1.jpg', productCount: 12 },
  { id: '3', name: 'مكياج', nameEn: 'Makeup', slug: 'makeup', image: '/image/products/mkg1.jpg', productCount: 12 },
  { id: '4', name: 'مجموعات الهدايا', nameEn: 'Gift Sets', slug: 'gift-sets', image: '/image/categories/acc7.jpg', productCount: 8 },
]

export const defaultSettings: SiteSettings = {
  storeName: 'سيدرا',
  storeNameEn: 'SEDRA',
  currency: 'USD',
  exchangeRate: 124,
  freeShippingThreshold: 100,
  shippingCost: 5,
  contactEmail: 'info@lipikaar.com',
  contactPhone: '+963 999 123 456',
  instagramUrl: 'https://www.instagram.com/sedra.chic?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
  facebookUrl: 'https://www.facebook.com/share/1DnS8WEjCR/',
  whatsappUrl: 'https://wa.me/+963950534327',
  heroTitle: 'اكتشفي أناقتك مع SEDRA',
  heroSubtitle: 'تشكيلة فريدة من المنتجات الراقية بأسعار مناسبة',
  announcement: 'شحن مجاني للطلبات فوق 50$ | خصم 10% على المجموعة الجديدة',
  announcementActive: true,
}

export const defaultCoupons: Coupon[] = [
  {
    id: '1',
    code: 'WELCOME20',
    type: 'percentage',
    value: 20,
    minPurchase: 50,
    maxUses: 100,
    usedCount: 23,
    active: true,
    expiresAt: '2026-12-31',
    createdAt: '2026-01-01',
  },
  {
    id: '2',
    code: 'SAVE10',
    type: 'fixed',
    value: 10,
    minPurchase: 75,
    maxUses: 50,
    usedCount: 12,
    active: true,
    expiresAt: '2026-06-30',
    createdAt: '2026-03-01',
  },
]

export const products: Product[] = [
  // Dresses (12 products)
  {
    id: 'p1',
    name: 'فستان سهرة مطرز بالذهبي',
    nameEn: 'Golden Embroidered Evening Dress',
    description: 'فستان سهرة فاخر مطرز يدوياً بخيوط ذهبية، مثالي للمناسبات الخاصة والحفلات',
    descriptionEn: 'Luxurious hand-embroidered evening dress with golden threads, perfect for special occasions',
    price: 89,
    originalPrice: 50,
    category: 'accessories',
    images: ['/image/categories/acc.jpg'],
    stock: 15,
    featured: true,
    bestSeller: true,
    newArrival: false,
    colors: ['ذهبي', 'فضي', 'أسود'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 127,
    createdAt: '2026-01-15',
  },
  {
    id: 'p2',
    name: 'فستان كاجوال صيفي',
    nameEn: 'Summer Casual Dress',
    description: 'فستان صيفي خفيف ومريح من القطن الطبيعي، مناسب للإطلالات اليومية',
    descriptionEn: 'Light and comfortable summer dress made from natural cotton',
    price: 65,
    category: 'accessories',
    images: ['/image/products/mkg5.jpg'],
    stock: 30,
    featured: false,
    bestSeller: true,
    newArrival: true,
    colors: ['وردي', 'أبيض', 'أزرق فاتح'],
    sizes: ['S', 'M', 'L'],
    rating: 4.7,
    reviewCount: 89,
    createdAt: '2026-03-01',
  },
  {
    id: 'p19',
    name: 'بلوزة شيفون شفافة',
    nameEn: 'Sheer Chiffon Blouse',
    description: 'بلوزة شيفون خفيفة بأكمام طويلة',
    descriptionEn: 'Light chiffon blouse with long sleeves',
    price: 60,
    category: 'perfumes',
    images: ['/image/categories/acc7.jpg'],
    stock: 22,
    featured: false,
    bestSeller: false,
    newArrival: true,
    colors: ['أبيض', 'أسود', 'وردي فاتح'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.3,
    reviewCount: 21,
    createdAt: '2026-03-18',
  },
  {
    id: 'p20',
    name: 'بلوزة كروب أنيقة',
    nameEn: 'Elegant Crop Blouse',
    description: 'بلوزة كروب قصيرة بتصميم عصري',
    descriptionEn: 'Short crop blouse with modern design',
    price: 50,
    category: 'perfumes',
    images: ['/image/products/mkg3.jpg'],
    stock: 30,
    featured: false,
    bestSeller: false,
    newArrival: false,
    colors: ['أسود', 'أبيض', 'أحمر'],
    sizes: ['S', 'M', 'L'],
    rating: 4.4,
    reviewCount: 33,
    createdAt: '2026-02-20',
  },
  // Skirts (6 products)
  {
    id: 'p21',
    name: 'تنورة ميدي بليسيه',
    nameEn: 'Pleated Midi Skirt',
    description: 'تنورة ميدي بطيات أنيقة وقماش متدفق',
    descriptionEn: 'Midi skirt with elegant pleats and flowing fabric',
    price: 65,
    originalPrice: 85,
    category: 'makeup',
    images: ['/image/categories/acc2.jpg'],
    stock: 18,
    featured: true,
    bestSeller: true,
    newArrival: false,
    colors: ['بيج', 'أسود', 'كحلي'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 58,
    createdAt: '2026-02-05',
  },
  {
    id: 'p22',
    name: 'تنورة جلد قصيرة',
    nameEn: 'Short Leather Skirt',
    description: 'تنورة قصيرة من الجلد الصناعي بقصة A-line',
    descriptionEn: 'Short faux leather skirt with A-line cut',
    price: 55,
    category: 'makeup',
    images: ['/image/categories/acc6.jpg'],
    stock: 20,
    featured: false,
    bestSeller: false,
    newArrival: true,
    colors: ['أسود', 'عنابي', 'بني'],
    sizes: ['S', 'M', 'L'],
    rating: 4.5,
    reviewCount: 42,
    createdAt: '2026-03-08',
  },
  {
    id: 'p23',
    name: 'تنورة ماكسي مزخرفة',
    nameEn: 'Patterned Maxi Skirt',
    description: 'تنورة طويلة بنقشات عصرية وخصر مطاطي',
    descriptionEn: 'Long skirt with modern patterns and elastic waist',
    price: 70,
    category: 'makeup',
    images: ['/image/products/mkg4.jpg'],
    stock: 15,
    featured: false,
    bestSeller: true,
    newArrival: false,
    colors: ['متعدد الألوان'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviewCount: 37,
    createdAt: '2026-01-18',
  },
  {
    id: 'p24',
    name: 'تنورة قلم رصاص',
    nameEn: 'Pencil Skirt',
    description: 'تنورة قلم رصاص ضيقة للإطلالات الرسمية',
    descriptionEn: 'Tight pencil skirt for formal looks',
    price: 60,
    category: 'makeup',
    images: ['/image/products/sh2.jpg'],
    stock: 22,
    featured: false,
    bestSeller: false,
    newArrival: false,
    colors: ['أسود', 'كحلي', 'رمادي'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.4,
    reviewCount: 29,
    createdAt: '2026-02-12',
  },
  {
    id: 'p25',
    name: 'تنورة دنيم كاجوال',
    nameEn: 'Casual Denim Skirt',
    description: 'تنورة جينز قصيرة بأزرار أمامية',
    descriptionEn: 'Short denim skirt with front buttons',
    price: 50,
    category: 'makeup',
    images: ['/image/products/sh1.jpg'],
    stock: 28,
    featured: false,
    bestSeller: false,
    newArrival: true,
    colors: ['أزرق فاتح', 'أزرق داكن'],
    sizes: ['S', 'M', 'L'],
    rating: 4.3,
    reviewCount: 24,
    createdAt: '2026-03-22',
  },
  {
    id: 'p26',
    name: 'تنورة تول فاخرة',
    nameEn: 'Luxury Tulle Skirt',
    description: 'تنورة تول منفوشة للمناسبات الخاصة',
    descriptionEn: 'Puffy tulle skirt for special occasions',
    price: 95,
    originalPrice: 90,
    category: 'makeup',
    images: ['/image/products/sh4.jpg'],
    stock: 10,
    featured: true,
    bestSeller: false,
    newArrival: false,
    colors: ['وردي', 'أبيض', 'أسود'],
    sizes: ['S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 19,
    createdAt: '2026-01-30',
  },
  // Accessories (4 products)
  {
    id: 'p39',
    name: 'حقيبة يد جلدية فاخرة',
    nameEn: 'Luxury Leather Handbag',
    description: 'حقيبة يد من الجلد الطبيعي بتصميم كلاسيكي',
    descriptionEn: 'Genuine leather handbag with classic design',
    price: 45,
    originalPrice: 90,
    category: 'gift-sets',
    images: ['/image/categories/acc3.jpg'],
    stock: 15,
    featured: true,
    bestSeller: true,
    newArrival: false,
    colors: ['أسود', 'بني', 'بيج'],
    rating: 4.8,
    reviewCount: 76,
    createdAt: '2026-01-15',
  },
  {
    id: 'p42',
    name: 'أقراط لؤلؤ أنيقة',
    nameEn: 'Elegant Pearl Earrings',
    description: 'أقراط من اللؤلؤ الصناعي بتصميم راقي',
    descriptionEn: 'Faux pearl earrings with elegant design',
    price: 35,
    category: 'gift-sets',
    images: ['/image/categories/acc6.jpg'],
    stock: 40,
    featured: false,
    bestSeller: false,
    newArrival: true,
    colors: ['أبيض', 'ذهبي'],
    rating: 4.5,
    reviewCount: 44,
    createdAt: '2026-03-10',
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured)
}

export function getBestSellers(): Product[] {
  return products.filter(p => p.bestSeller)
}

export function getNewArrivals(): Product[] {
  return products.filter(p => p.newArrival)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(p => 
    p.name.toLowerCase().includes(lowerQuery) ||
    p.nameEn.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.descriptionEn.toLowerCase().includes(lowerQuery)
  )
}
